version: '3'
services:
  client:
    build:
      context: ./client
      args:
        REACT_APP_API: /api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    links:
      - api
    environment:
      REACT_APP_API: /api

  api:
    build: ./server
    ports:
      - 4000:4000
    environment:
      APP_API: /api
      DB_HOST: postgres
      DB_USER: pdadmin
      DB_PASSWORD: 123456
      DB_NAME: parkdepotdb
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: pdadmin
      POSTGRES_DB: parkdepotdb

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
